// Generated from TabelaRate.xlsx. Source of truth for Rate FAUS official matrix.
export const RATE_CRITERION_LIBRARY = [
  {
    axis: "Processos",
    criteria: [
      {
        criterion: "Mapeamento de processos",
        description: "Existência, detalhamento, atualização",
        scale: {
          1: "1- Não existem processos mapeados. A operação funciona com base em conhecimento tácito, experiência individual e improviso.",
          2: "2- Existem mapeamentos pontuais ou informais, incompletos e que não refletem fielmente a prática operacional.",
          3: "3- Processos mapeados, porém com baixo detalhamento, desatualizados ou pouco utilizados.",
          4: "4- Processos mapeados, detalhados, atualizados e utilizados como referência operacional.",
          5: "5- Mapeamento completo, governado, integrado à gestão e utilizado como base oficial da operação.",
        },
      },
      {
        criterion: "Padronização",
        description: "Documentação e uso real",
        scale: {
          1: "1- Inexistência de padrões formais. Execução varia conforme pessoas e turnos.",
          2: "2- Padrões informais ou pouco difundidos, sem uso consistente.",
          3: "3- Padrões documentados, porém com baixa aderência na prática.",
          4: "4- Padrões claros, documentados e utilizados regularmente na operação.",
          5: "5- Padronização madura, integrada à cultura e continuamente aprimorada.",
        },
      },
      {
        criterion: "Trabalho padronizado",
        description: "Rotinas claras",
        scale: {
          1: "1- Ausência de rotinas claras. Execução altamente variável.",
          2: "2- Rotinas implícitas ou verbais, dependentes da experiência individual.",
          3: "3- Rotinas definidas, porém seguidas de forma inconsistente.",
          4: "4- Rotinas claras, padronizadas e seguidas de forma disciplinada.",
          5: "5- Trabalho padronizado robusto, base da produtividade e melhoria contínua.",
        },
      },
      {
        criterion: "Controles operacionais",
        description: "Checklists, auditorias",
        scale: {
          1: "1- Inexistência de controles formais.",
          2: "2- Controles pontuais e informais, sem método.",
          3: "3- Controles definidos, porém aplicados de forma irregular.",
          4: "4- Checklists e auditorias aplicados regularmente para correção de desvios.",
          5: "5- Controles sistemáticos, gerando aprendizado e prevenção de falhas.",
        },
      },
      {
        criterion: "Aderência ao processo",
        description: "Execução real vs. processo",
        scale: {
          1: "1- Execução não aderente aos processos definidos.",
          2: "2- Aderência parcial, com desvios frequentes.",
          3: "3- Aderência majoritária, porém instável.",
          4: "4- Alta aderência, com tratamento estruturado de desvios.",
          5: "5- Aderência plena e disciplinada entre processo e execução.",
        },
      },
      {
        criterion: "Medição de desempenho",
        description: "Medição contínua de resultados",
        scale: {
          1: "1- Inexistência de indicadores de processo.",
          2: "2- Medições pontuais e reativas.",
          3: "3- Indicadores definidos, porém pouco utilizados.",
          4: "4- Medição contínua orientando decisões e melhorias.",
          5: "5- Medição integrada à gestão e ciclos de melhoria contínua.",
        },
      },
    ],
  },
  {
    axis: "Operação",
    criteria: [
      {
        criterion: "Slotting e layout",
        description: "Otimização do espaço e fluxo de produtos",
        scale: {
          1: "1- Não existe lógica definida de slotting ou layout. O armazenamento ocorre de forma aleatória, gerando deslocamentos excessivos, congestionamentos e baixa produtividade.",
          2: "2- Existe alguma lógica básica de layout, porém sem critérios claros de giro, peso ou frequência. O fluxo ainda é ineficiente e reativo.",
          3: "3- O layout e o slotting estão definidos, porém com limitações. A organização reduz alguns desperdícios, mas não é revisada com frequência.",
          4: "4- Layout e slotting estruturados, considerando giro, peso e fluxo. Reduz deslocamentos, melhora produtividade e é revisado periodicamente.",
          5: "5- Layout e slotting altamente otimizados, baseados em dados, revisados continuamente e alinhados à estratégia operacional.",
        },
      },
      {
        criterion: "Acuracidade de inventário",
        description: "Processos de contagem e verificação",
        scale: {
          1: "1- Não existem processos formais de inventário. As informações de estoque são pouco confiáveis.",
          2: "2- Existem contagens pontuais ou inventários esporádicos, com alto índice de divergência.",
          3: "3- Inventários e contagens cíclicas definidos, porém com resultados instáveis e ações corretivas limitadas.",
          4: "4- Processos de contagem estruturados, com boa acuracidade e tratamento sistemático de divergências.",
          5: "5- Acuracidade elevada e estável, com inventário confiável e integrado à gestão e decisão.",
        },
      },
      {
        criterion: "Produtividade no picking",
        description: "Eficiência na separação de pedidos",
        scale: {
          1: "1- Não existe medição de produtividade. O picking depende de esforço individual.",
          2: "2- A produtividade é percebida de forma empírica, sem metas ou controle estruturado.",
          3: "3- A produtividade é medida, porém com uso limitado e grande variabilidade entre turnos.",
          4: "4- Produtividade acompanhada com indicadores, metas claras e ações de melhoria.",
          5: "5- Alta produtividade estável, com métodos otimizados, padronização e melhoria contínua.",
        },
      },
      {
        criterion: "Lead times operacionais",
        description: "Tempo entre etapas do processo",
        scale: {
          1: "1- Não existe controle de tempos entre etapas. O processo é imprevisível.",
          2: "2- Existem estimativas informais de tempo, sem medição consistente.",
          3: "3- Lead times medidos, porém com alta variabilidade e pouca gestão sobre desvios.",
          4: "4- Lead times controlados, com metas, monitoramento e redução de gargalos.",
          5: "5- Lead times previsíveis, estáveis e continuamente otimizados.",
        },
      },
      {
        criterion: "Controle de qualidade",
        description: "Acuracidade na separação e conferência",
        scale: {
          1: "1- Não existem controles formais de qualidade. Erros são frequentes.",
          2: "2- Controles pontuais ou reativos após reclamações.",
          3: "3- Controles definidos, porém com falhas recorrentes e ações pouco estruturadas.",
          4: "4- Controles eficazes, com redução consistente de erros e ações corretivas.",
          5: "5- Qualidade elevada e estável, com erros raros e aprendizado contínuo.",
        },
      },
      {
        criterion: "Gestão de falhas e exceções",
        description: "Tratamento de falhas operacionais",
        scale: {
          1: "1- Falhas são tratadas apenas de forma emergencial, sem análise estruturada.",
          2: "2- Existe reação às falhas, porém sem registro ou aprendizado.",
          3: "3- Falhas registradas, mas com análise superficial e repetição recorrente.",
          4: "4- Falhas tratadas com método, análise de causa e ações corretivas.",
          5: "5- Gestão madura de exceções, com prevenção, aprendizado e melhoria sistêmica.",
        },
      },
    ],
  },
  {
    axis: "Tecnologia",
    criteria: [
      {
        criterion: "Integração de sistemas",
        description: "Conectividade entre ERP, WMS e TMS",
        scale: {
          1: "1- Sistemas não integrados. Informações fragmentadas e controles manuais paralelos.",
          2: "2- Integração pontual ou parcial entre sistemas, com falhas frequentes.",
          3: "3- Sistemas integrados em partes críticas, porém com dependência de planilhas.",
          4: "4- Integração consistente entre ERP, WMS e TMS, com dados confiáveis.",
          5: "5- Integração total, dados em tempo quase real e suporte pleno à decisão.",
        },
      },
      {
        criterion: "Sistemas de rastreamento",
        description: "Telemetria e rastreadores",
        scale: {
          1: "1- Não há rastreamento estruturado de veículos ou cargas.",
          2: "2- Rastreamento limitado, com baixa confiabilidade ou uso esporádico.",
          3: "3- Rastreamento ativo, porém pouco integrado à gestão.",
          4: "4- Rastreamento confiável, integrado à operação e gestão de ocorrências.",
          5: "5- Rastreamento avançado, com análise de dados e prevenção de falhas.",
        },
      },
      {
        criterion: "Automação de processos",
        description: "Automação para produtividade",
        scale: {
          1: "1- Processos totalmente manuais e dependentes de esforço humano.",
          2: "2- Automação pontual, sem impacto relevante na produtividade.",
          3: "3- Automação em etapas-chave, porém com limitações.",
          4: "4- Automação consistente, reduzindo erros e aumentando eficiência.",
          5: "5- Automação avançada, integrada e orientada por dados.",
        },
      },
      {
        criterion: "Dashboards e relatórios",
        description: "Visualização em tempo real",
        scale: {
          1: "1- Ausência de dashboards. Informações dispersas e tardias.",
          2: "2- Relatórios manuais, pouco frequentes e pouco confiáveis.",
          3: "3- Dashboards existentes, porém com uso restrito.",
          4: "4- Dashboards confiáveis, atualizados e utilizados na gestão.",
          5: "5- Visualização em tempo real integrada à tomada de decisão.",
        },
      },
      {
        criterion: "Big Data e análise preditiva",
        description: "Previsão de tendências e riscos",
        scale: {
          1: "1- Não existe uso analítico dos dados.",
          2: "2- Uso básico e descritivo de dados históricos.",
          3: "3- Análises exploratórias pontuais.",
          4: "4- Uso analítico para antecipar problemas e tendências.",
          5: "5- Análise preditiva madura, integrada à estratégia.",
        },
      },
    ],
  },
  {
    axis: "Gestão",
    criteria: [
      {
        criterion: "Planejamento estratégico",
        description: "Gestão de recursos e visão de longo prazo",
        scale: {
          1: "1- Inexistência de planejamento estratégico. Decisões reativas e de curto prazo.",
          2: "2- Planejamento informal, pouco documentado e sem desdobramento claro.",
          3: "3- Planejamento definido, porém pouco conectado à operação.",
          4: "4- Planejamento estruturado, com metas, recursos e acompanhamento.",
          5: "5- Planejamento estratégico robusto, integrado à operação e revisado continuamente.",
        },
      },
      {
        criterion: "KPIs e métricas",
        description: "Indicadores estratégicos e operacionais",
        scale: {
          1: "1- Inexistência de indicadores formais.",
          2: "2- Indicadores pontuais, pouco confiáveis ou pouco utilizados.",
          3: "3- Indicadores definidos, porém com uso restrito.",
          4: "4- Indicadores confiáveis, utilizados regularmente na gestão.",
          5: "5- KPIs integrados à tomada de decisão estratégica e operacional.",
        },
      },
      {
        criterion: "Gestão de equipes",
        description: "Liderança e desenvolvimento",
        scale: {
          1: "1- Gestão baseada apenas em cobrança e esforço individual.",
          2: "2- Liderança informal, com pouco desenvolvimento estruturado.",
          3: "3- Gestão estruturada, porém com desenvolvimento limitado.",
          4: "4- Liderança ativa, com acompanhamento e desenvolvimento contínuo.",
          5: "5- Times de alta performance, engajados e desenvolvidos.",
        },
      },
      {
        criterion: "PDCA e melhoria contínua",
        description: "Ciclos estruturados de melhoria",
        scale: {
          1: "1- Inexistência de método de melhoria.",
          2: "2- Ações corretivas pontuais e reativas.",
          3: "3- Uso ocasional do PDCA, sem disciplina.",
          4: "4- PDCA aplicado de forma estruturada e recorrente.",
          5: "5- Cultura de melhoria contínua madura e disciplinada.",
        },
      },
      {
        criterion: "Gestão visual e comunicação",
        description: "Comunicação e acompanhamento",
        scale: {
          1: "1- Comunicação desestruturada e pouco clara.",
          2: "2- Informações compartilhadas de forma informal.",
          3: "3- Gestão visual existente, porém pouco utilizada.",
          4: "4- Gestão visual clara, utilizada no acompanhamento.",
          5: "5- Comunicação visual integrada à rotina e decisões.",
        },
      },
      {
        criterion: "Gestão de riscos",
        description: "Riscos operacionais e financeiros",
        scale: {
          1: "1- Inexistência de gestão de riscos.",
          2: "2- Riscos conhecidos, mas não tratados sistematicamente.",
          3: "3- Gestão de riscos parcial e reativa.",
          4: "4- Riscos mapeados, monitorados e mitigados.",
          5: "5- Gestão de riscos madura, integrada à estratégia.",
        },
      },
    ],
  },
  {
    axis: "Cultura",
    criteria: [
      {
        criterion: "Responsabilidade e accountability",
        description: "Assunção de responsabilidades",
        scale: {
          1: "1- Não há clareza de responsabilidades. Erros são recorrentes e não assumidos.",
          2: "2- Responsabilidades pouco claras, com transferência frequente de culpa.",
          3: "3- Responsabilidades definidas, porém com baixa cobrança e acompanhamento.",
          4: "4- Responsabilidades claras, com cobrança estruturada e comprometimento.",
          5: "5- Alta accountability, com forte senso de dono e foco em resultados.",
        },
      },
      {
        criterion: "Disciplina operacional",
        description: "Aderência a rotinas",
        scale: {
          1: "1- Ausência de disciplina. Rotinas não são seguidas.",
          2: "2- Disciplina pontual, dependente de cobrança direta.",
          3: "3- Rotinas definidas, porém com aderência instável.",
          4: "4- Disciplina consistente, com rotinas seguidas regularmente.",
          5: "5- Disciplina elevada, incorporada à cultura e sustentada no tempo.",
        },
      },
      {
        criterion: "Abertura à inovação",
        description: "Adoção de melhorias",
        scale: {
          1: "1- Resistência a mudanças e melhorias.",
          2: "2- Abertura limitada, com adoção lenta de melhorias.",
          3: "3- Melhorias aceitas pontualmente, sem método estruturado.",
          4: "4- Abertura consistente a melhorias e inovações.",
          5: "5- Cultura inovadora, com melhoria contínua incorporada.",
        },
      },
      {
        criterion: "Gestão do tempo",
        description: "Uso eficiente do tempo",
        scale: {
          1: "1- Uso ineficiente do tempo, com atrasos frequentes.",
          2: "2- Gestão de tempo reativa e pouco planejada.",
          3: "3- Planejamento básico do tempo, com falhas recorrentes.",
          4: "4- Boa gestão do tempo, com prioridades claras.",
          5: "5- Gestão do tempo madura, com foco em valor e produtividade.",
        },
      },
    ],
  },
  {
    axis: "Custos",
    criteria: [
      {
        criterion: "Custo por unidade de carga",
        description: "Custo por m², kg, pedido",
        scale: {
          1: "1- A empresa não conhece seus custos unitários. Não há cálculo por m², kg, pedido ou entrega.",
          2: "2- Existem estimativas aproximadas de custos unitários, sem método estruturado ou confiabilidade.",
          3: "3- Custos unitários calculados, porém com baixa granularidade ou atualização esporádica.",
          4: "4- Custos unitários bem definidos, atualizados e utilizados para análise e controle.",
          5: "5- Custos unitários precisos, integrados à gestão e utilizados para decisões estratégicas.",
        },
      },
      {
        criterion: "Custos fixos e variáveis",
        description: "Controle e distinção",
        scale: {
          1: "1- Não há distinção clara entre custos fixos e variáveis.",
          2: "2- Distinção básica, porém sem controle efetivo ou análise de impacto.",
          3: "3- Custos classificados, mas com uso limitado para gestão.",
          4: "4- Custos fixos e variáveis bem controlados e analisados regularmente.",
          5: "5- Gestão madura de custos, com simulações e decisões baseadas na estrutura de custos.",
        },
      },
      {
        criterion: "Rentabilidade operacional",
        description: "Rentabilidade por operação",
        scale: {
          1: "1- A empresa não mede rentabilidade por operação ou centro de custo.",
          2: "2- Rentabilidade analisada apenas em nível global.",
          3: "3- Rentabilidade por operação calculada pontualmente.",
          4: "4- Rentabilidade operacional acompanhada regularmente.",
          5: "5- Rentabilidade integrada à estratégia e tomada de decisão.",
        },
      },
      {
        criterion: "Análise custo-benefício",
        description: "Decisão baseada em valor",
        scale: {
          1: "1- Decisões tomadas sem análise de custo-benefício.",
          2: "2- Análises intuitivas ou superficiais.",
          3: "3- Análises realizadas de forma pontual.",
          4: "4- Análise custo-benefício estruturada antes das decisões.",
          5: "5- Cultura decisória baseada em valor e retorno.",
        },
      },
    ],
  },
  {
    axis: "Logística de Transporte",
    criteria: [
      {
        criterion: "Custo por km",
        description: "Custo por km rodado",
        scale: {
          1: "1- A empresa não conhece o custo por km rodado. Não há controle econômico do transporte.",
          2: "2- Existem estimativas genéricas de custo por km, sem método estruturado ou confiabilidade.",
          3: "3- Custo por km calculado, porém com atualização esporádica ou baixa granularidade.",
          4: "4- Custo por km bem definido, atualizado e utilizado na gestão e controle do transporte.",
          5: "5- Custo por km preciso, integrado à decisão estratégica, negociação e otimização.",
        },
      },
      {
        criterion: "Roteirização otimizada",
        description: "Otimização de rotas",
        scale: {
          1: "1- As rotas são definidas de forma empírica, sem critérios claros.",
          2: "2- Existe alguma lógica básica de roteirização, porém reativa e pouco eficiente.",
          3: "3- Roteirização estruturada, porém com baixa otimização ou revisão esporádica.",
          4: "4- Rotas otimizadas considerando distância, capacidade e restrições operacionais.",
          5: "5- Roteirização avançada, baseada em dados, revisada continuamente e integrada à estratégia.",
        },
      },
      {
        criterion: "Gestão da frota",
        description: "Gestão frota própria/terceiros",
        scale: {
          1: "1- Gestão inexistente ou totalmente reativa da frota.",
          2: "2- Gestão básica da frota, com controles limitados e pouca análise.",
          3: "3- Gestão estruturada, porém com uso limitado de indicadores.",
          4: "4- Gestão eficiente da frota, com indicadores, controle e decisões consistentes.",
          5: "5- Gestão madura da frota, integrada a custos, serviço e estratégia.",
        },
      },
      {
        criterion: "Nível de serviço de entrega",
        description: "Cumprimento de prazos",
        scale: {
          1: "1- O nível de serviço não é medido. Atrasos são frequentes.",
          2: "2- O nível de serviço é percebido, mas não medido sistematicamente.",
          3: "3- O nível de serviço é medido, porém com falhas recorrentes.",
          4: "4- Bom nível de serviço, acompanhado e com ações corretivas.",
          5: "5- Alto nível de serviço, estável e sustentado por método.",
        },
      },
      {
        criterion: "Telemetria e rastreadores",
        description: "Monitoramento veicular",
        scale: {
          1: "1- Não existe monitoramento veicular estruturado.",
          2: "2- Monitoramento pontual ou pouco confiável.",
          3: "3- Telemetria utilizada, porém com baixo uso gerencial.",
          4: "4- Telemetria integrada à gestão e ao controle operacional.",
          5: "5- Uso avançado de telemetria para prevenção, segurança e eficiência.",
        },
      },
    ],
  },
  {
    axis: "Controle de Estoque",
    criteria: [
      {
        criterion: "Estratégias de estoque",
        description: "Níveis e reposição",
        scale: {
          1: "1- Não existem estratégias definidas de estoque. Reposição reativa e sem critérios.",
          2: "2- Existem regras básicas de reposição, porém pouco estruturadas.",
          3: "3- Estratégias definidas, mas com baixa aderência ou revisão esporádica.",
          4: "4- Estratégias claras de estoque, com níveis e reposição bem definidos.",
          5: "5- Gestão estratégica de estoques integrada à demanda, custo e serviço.",
        },
      },
      {
        criterion: "Acuracidade de estoque",
        description: "Exatidão do inventário",
        scale: {
          1: "1- Inventário pouco confiável, com divergências frequentes.",
          2: "2- Controles básicos de estoque, com alta variabilidade.",
          3: "3- Inventário estruturado, porém com inconsistências recorrentes.",
          4: "4- Alta acuracidade de estoque, com controle e correção sistemática.",
          5: "5- Acuracidade elevada e estável, integrada à gestão e decisão.",
        },
      },
      {
        criterion: "Gestão de rupturas",
        description: "Prevenção e resolução",
        scale: {
          1: "1- Rupturas frequentes e tratadas apenas de forma emergencial.",
          2: "2- Rupturas conhecidas, porém sem análise estruturada.",
          3: "3- Rupturas monitoradas, mas com ações corretivas limitadas.",
          4: "4- Gestão estruturada de rupturas, com prevenção e correção.",
          5: "5- Rupturas raras, com gestão preditiva e aprendizado contínuo.",
        },
      },
      {
        criterion: "Rotatividade de produtos",
        description: "Giro de estoque",
        scale: {
          1: "1- Não existe controle de giro ou produtos obsoletos.",
          2: "2- Giro percebido de forma empírica.",
          3: "3- Giro medido, porém com uso limitado para decisão.",
          4: "4- Giro acompanhado e utilizado para ajustes de estoque.",
          5: "5- Giro otimizado, alinhado à estratégia e rentabilidade.",
        },
      },
      {
        criterion: "Métodos de armazenamento",
        description: "Otimização de espaço",
        scale: {
          1: "1- Armazenamento desorganizado, sem método definido.",
          2: "2- Métodos básicos de armazenamento, pouco otimizados.",
          3: "3- Métodos definidos, porém com uso ineficiente do espaço.",
          4: "4- Armazenamento organizado, com boa utilização do espaço.",
          5: "5- Métodos avançados, maximizando espaço, fluxo e produtividade.",
        },
      },
    ],
  },
] as const

export const RATE_PROFILE_WEIGHTS = {
  distribuidor: {
    "Processos": {
      "Mapeamento de processos": 0.02,
      "Padronização": 0.03,
      "Trabalho padronizado": 0.03,
      "Controles operacionais": 0.02,
      "Aderência ao processo": 0.03,
      "Medição de desempenho": 0.02,
    },
    "Operação": {
      "Slotting e layout": 0.03,
      "Acuracidade de inventário": 0.03,
      "Produtividade no picking": 0.04,
      "Lead times operacionais": 0.04,
      "Controle de qualidade": 0.03,
      "Gestão de falhas e exceções": 0.03,
    },
    "Tecnologia": {
      "Integração de sistemas": 0.03,
      "Sistemas de rastreamento": 0.02,
      "Automação de processos": 0.02,
      "Dashboards e relatórios": 0.02,
      "Big Data e análise preditiva": 0.01,
    },
    "Gestão": {
      "Planejamento estratégico": 0.03,
      "KPIs e métricas": 0.04,
      "Gestão de equipes": 0.04,
      "PDCA e melhoria contínua": 0.04,
      "Gestão visual e comunicação": 0.03,
      "Gestão de riscos": 0.02,
    },
    "Cultura": {
      "Responsabilidade e accountability": 0.03,
      "Disciplina operacional": 0.03,
      "Abertura à inovação": 0.02,
      "Gestão do tempo": 0.02,
    },
    "Custos": {
      "Custo por unidade de carga": 0.03,
      "Custos fixos e variáveis": 0.03,
      "Rentabilidade operacional": 0.02,
      "Análise custo-benefício": 0.02,
    },
    "Logística de Transporte": {
      "Custo por km": 0.03,
      "Roteirização otimizada": 0.03,
      "Gestão da frota": 0.02,
      "Nível de serviço de entrega": 0.01,
      "Telemetria e rastreadores": 0.01,
    },
    "Controle de Estoque": {
      "Estratégias de estoque": 0.015,
      "Acuracidade de estoque": 0.015,
      "Gestão de rupturas": 0.01,
      "Rotatividade de produtos": 0.005,
      "Métodos de armazenamento": 0.005,
    },
  },
  industria: {
    "Processos": {
      "Mapeamento de processos": 0.025,
      "Padronização": 0.035,
      "Trabalho padronizado": 0.035,
      "Controles operacionais": 0.025,
      "Aderência ao processo": 0.03,
      "Medição de desempenho": 0.03,
    },
    "Operação": {
      "Slotting e layout": 0.03,
      "Acuracidade de inventário": 0.03,
      "Produtividade no picking": 0.035,
      "Lead times operacionais": 0.035,
      "Controle de qualidade": 0.025,
      "Gestão de falhas e exceções": 0.025,
    },
    "Tecnologia": {
      "Integração de sistemas": 0.03,
      "Sistemas de rastreamento": 0.02,
      "Automação de processos": 0.02,
      "Dashboards e relatórios": 0.02,
      "Big Data e análise preditiva": 0.01,
    },
    "Gestão": {
      "Planejamento estratégico": 0.035,
      "KPIs e métricas": 0.04,
      "Gestão de equipes": 0.04,
      "PDCA e melhoria contínua": 0.04,
      "Gestão visual e comunicação": 0.03,
      "Gestão de riscos": 0.025,
    },
    "Cultura": {
      "Responsabilidade e accountability": 0.03,
      "Disciplina operacional": 0.03,
      "Abertura à inovação": 0.02,
      "Gestão do tempo": 0.02,
    },
    "Custos": {
      "Custo por unidade de carga": 0.03,
      "Custos fixos e variáveis": 0.03,
      "Rentabilidade operacional": 0.03,
      "Análise custo-benefício": 0.03,
    },
    "Logística de Transporte": {
      "Custo por km": 0.02,
      "Roteirização otimizada": 0.02,
      "Gestão da frota": 0.015,
      "Nível de serviço de entrega": 0.01,
      "Telemetria e rastreadores": 0.01,
    },
    "Controle de Estoque": {
      "Estratégias de estoque": 0.015,
      "Acuracidade de estoque": 0.015,
      "Gestão de rupturas": 0.01,
      "Rotatividade de produtos": 0.005,
      "Métodos de armazenamento": 0.005,
    },
  },
  operador_logistico: {
    "Processos": {
      "Mapeamento de processos": 0.03,
      "Padronização": 0.035,
      "Trabalho padronizado": 0.035,
      "Controles operacionais": 0.03,
      "Aderência ao processo": 0.035,
      "Medição de desempenho": 0.035,
    },
    "Operação": {
      "Slotting e layout": 0.035,
      "Acuracidade de inventário": 0.03,
      "Produtividade no picking": 0.04,
      "Lead times operacionais": 0.04,
      "Controle de qualidade": 0.03,
      "Gestão de falhas e exceções": 0.03,
    },
    "Tecnologia": {
      "Integração de sistemas": 0.04,
      "Sistemas de rastreamento": 0.03,
      "Automação de processos": 0.03,
      "Dashboards e relatórios": 0.02,
      "Big Data e análise preditiva": 0.02,
    },
    "Gestão": {
      "Planejamento estratégico": 0.03,
      "KPIs e métricas": 0.035,
      "Gestão de equipes": 0.035,
      "PDCA e melhoria contínua": 0.035,
      "Gestão visual e comunicação": 0.025,
      "Gestão de riscos": 0.02,
    },
    "Cultura": {
      "Responsabilidade e accountability": 0.03,
      "Disciplina operacional": 0.03,
      "Abertura à inovação": 0.02,
      "Gestão do tempo": 0.02,
    },
    "Custos": {
      "Custo por unidade de carga": 0.025,
      "Custos fixos e variáveis": 0.025,
      "Rentabilidade operacional": 0.015,
      "Análise custo-benefício": 0.015,
    },
    "Logística de Transporte": {
      "Custo por km": 0.02,
      "Roteirização otimizada": 0.02,
      "Gestão da frota": 0.015,
      "Nível de serviço de entrega": 0.01,
      "Telemetria e rastreadores": 0.01,
    },
    "Controle de Estoque": {
      "Estratégias de estoque": 0.01,
      "Acuracidade de estoque": 0.01,
      "Gestão de rupturas": 0.005,
      "Rotatividade de produtos": 0.002,
      "Métodos de armazenamento": 0.003,
    },
  },
} as const
