import { StyleSheet } from '@react-pdf/renderer'

export const reportColors = {
  neon: '#0AFAB9',
  orange: '#DB6100',
  black: '#000000',
  white: '#FFFFFF',
  ink: '#2B2B2B',
  slate: '#4B5563',
  muted: '#6B7280',
  line: '#E5E7EB',
  soft: '#F3F4F6',
  softNeon: '#DDFEF4',
  softOrange: '#FFF1E7',
  red: '#B42318',
  softRed: '#FEE4E2',
}

export const reportStyles = StyleSheet.create({
  page: {
    paddingTop: 38,
    paddingRight: 34,
    paddingBottom: 42,
    paddingLeft: 34,
    fontFamily: 'Helvetica',
    fontSize: 9,
    color: reportColors.ink,
    backgroundColor: reportColors.white,
  },
  cover: {
    padding: 0,
    fontFamily: 'Helvetica',
    color: reportColors.white,
    backgroundColor: reportColors.black,
  },
  coverShell: {
    minHeight: '100%',
    padding: 38,
    backgroundColor: reportColors.black,
  },
  coverTop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
  },
  coverLogo: {
    width: 126,
    height: 42,
    objectFit: 'contain',
  },
  coverKicker: {
    fontSize: 8,
    letterSpacing: 2.4,
    textTransform: 'uppercase',
    color: reportColors.neon,
  },
  coverAccent: {
    marginTop: 54,
    width: 96,
    height: 4,
    backgroundColor: reportColors.neon,
  },
  coverOrangeAccent: {
    marginTop: 7,
    width: 34,
    height: 4,
    backgroundColor: reportColors.orange,
  },
  coverTitle: {
    marginTop: 28,
    maxWidth: 420,
    fontSize: 34,
    lineHeight: 1.08,
    fontWeight: 700,
  },
  coverSubtitle: {
    marginTop: 12,
    maxWidth: 380,
    fontSize: 12,
    lineHeight: 1.45,
    color: '#D1D5DB',
  },
  coverInfoPanel: {
    marginTop: 54,
    padding: 20,
    borderWidth: 1,
    borderColor: '#1F2937',
    borderRadius: 14,
    backgroundColor: '#111827',
  },
  coverInfoLabel: {
    fontSize: 7,
    letterSpacing: 1.6,
    textTransform: 'uppercase',
    color: reportColors.neon,
  },
  coverInfoValue: {
    marginTop: 4,
    marginBottom: 12,
    fontSize: 12,
    lineHeight: 1.35,
    color: reportColors.white,
  },
  coverFooter: {
    position: 'absolute',
    left: 38,
    right: 38,
    bottom: 34,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: '#1F2937',
    flexDirection: 'row',
    justifyContent: 'space-between',
    color: '#9CA3AF',
    fontSize: 8,
  },
  header: {
    marginBottom: 18,
    paddingBottom: 10,
    borderBottomWidth: 1,
    borderBottomColor: reportColors.line,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 16,
  },
  headerLogo: {
    width: 62,
    height: 22,
    objectFit: 'contain',
  },
  headerTitle: {
    fontSize: 12,
    fontWeight: 700,
    color: reportColors.black,
  },
  headerText: {
    marginTop: 3,
    fontSize: 8,
    color: reportColors.muted,
  },
  footer: {
    position: 'absolute',
    left: 34,
    right: 34,
    bottom: 20,
    paddingTop: 8,
    borderTopWidth: 1.4,
    borderTopColor: reportColors.neon,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    color: reportColors.muted,
    fontSize: 7.5,
  },
  footerBrand: {
    fontWeight: 700,
    color: reportColors.ink,
  },
  section: {
    marginBottom: 15,
  },
  sectionHeader: {
    marginBottom: 8,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 7,
  },
  sectionMark: {
    width: 4,
    height: 14,
    backgroundColor: reportColors.orange,
  },
  sectionTitle: {
    fontSize: 13,
    fontWeight: 700,
    color: reportColors.black,
  },
  paragraph: {
    lineHeight: 1.5,
    color: reportColors.slate,
  },
  grid: {
    flexDirection: 'row',
    gap: 8,
    marginBottom: 14,
  },
  metricCard: {
    flex: 1,
    padding: 11,
    borderWidth: 1,
    borderColor: reportColors.line,
    borderRadius: 10,
    backgroundColor: reportColors.white,
  },
  metricCardStrong: {
    borderColor: reportColors.neon,
    backgroundColor: reportColors.softNeon,
  },
  metricCardWarning: {
    borderColor: reportColors.orange,
    backgroundColor: reportColors.softOrange,
  },
  metricCardDanger: {
    borderColor: '#FCA5A5',
    backgroundColor: reportColors.softRed,
  },
  metricLabel: {
    fontSize: 7,
    textTransform: 'uppercase',
    letterSpacing: 0.8,
    color: reportColors.muted,
  },
  metricValue: {
    marginTop: 5,
    fontSize: 20,
    fontWeight: 700,
    color: reportColors.black,
  },
  table: {
    borderWidth: 1,
    borderColor: reportColors.line,
    borderRadius: 10,
    overflow: 'hidden',
  },
  tableHeader: {
    flexDirection: 'row',
    backgroundColor: reportColors.black,
    color: reportColors.white,
  },
  tableRow: {
    flexDirection: 'row',
    borderTopWidth: 1,
    borderTopColor: reportColors.line,
  },
  tableRowAlt: {
    backgroundColor: reportColors.soft,
  },
  tableCell: {
    padding: 7,
    fontSize: 8,
    lineHeight: 1.35,
    color: reportColors.ink,
  },
  tableHeaderCell: {
    padding: 7,
    fontSize: 7,
    fontWeight: 700,
    textTransform: 'uppercase',
    letterSpacing: 0.4,
  },
  emptyState: {
    padding: 14,
    borderWidth: 1,
    borderColor: reportColors.line,
    borderRadius: 10,
    backgroundColor: reportColors.soft,
    color: reportColors.muted,
  },
  badge: {
    paddingVertical: 3,
    paddingHorizontal: 6,
    borderRadius: 999,
    backgroundColor: reportColors.softNeon,
    color: reportColors.black,
    fontSize: 7,
  },
  moreNote: {
    marginTop: 7,
    fontSize: 8,
    color: reportColors.muted,
  },
})
